services:
  db:
    image: mysql
    restart: always
    secrets:
      - db-password
    volumes:
      - /db/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - shop-dev-network
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - /home/server/logs:/var/log
    networks:
      - shop-dev-network
    depends_on:
      db:
        condition: service_healthy
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - shop-dev-network
    depends_on:
      - server
    expose:
      - 3000
    environment:
      API_HOST: server

networks:
  shop-dev-network:
    driver: bridge

