server:
  port: ${PORT:8080}

spring:
  application:
    name: shop-dev-app
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: "jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: ${DB_TYPE}
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          serverTimezone: Asia/Ho_Chi_Minh
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: shop-dev-api-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
        # provider:
        #   google:
        #     authorization-uri: https://accounts.google.com/o/oauth2/auth
        #     token-uri: https://accounts.google.com/o/oauth2/token
        #     user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        #     user-name-attribute: sub
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-in-ms: ${JWT_EXPIRATION_IN_MS}

firebase:
  service-account-file: ${FIREBASE_SERVICE_ACCOUNT_FILE:firebase-credentials.json}

payos:
  api-key: ${PAYOS_API_KEY}
  api-secret: ${PAYOS_API_SECRET}
  endpoint: ${PAYOS_ENDPOINT}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG


