
server:
  port: 8080
spring:
  application:
    name: shop-dev-app
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


