server:
  port: 8080
spring:
  application:
    name: shop-dev-app
  datasource:
    url: "jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shopdev}?useSSL=false"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: ${DB_TYPE:mysql}
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          serverTimezone: Asia/Ho_Chi_Minh
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: shop-dev-api-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

firebase:
  service-account-file: ${FIREBASE_SERVICE_ACCOUNT_FILE:firebase-credentials.json}

payos:
  api-key: ${PAYOS_API_KEY}
  api-secret: ${PAYOS_API_SECRET}
  endpoint: ${PAYOS_ENDPOINT}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG


